### ISSUE TITLE
visualization issue

### ISSUE THREAD

**Issue by chenziyi-zzz** [VIS4ROB-lab/voxfield#6]
Thanks for your excellent work! 
I have a question about the result in your paper. How can I get the same visualization as Fig. 9?
![image](https://user-images.githubusercontent.com/55970174/223705889-375a879d-0373-4bf9-bb5a-eb693c2bedd1.png)

**Comment by YuePanEdward** [comment]
Thanks for your interest on our work.
This figure is generated using the code provided [here](https://github.com/VIS4ROB-lab/voxfield-panmap/blob/master/panoptic_mapping_utils/src/evaluation/map_evaluator.cpp#L791) with the built maps of each method.
