### ISSUE TITLE
Combine voxfield with voxgraph

### ISSUE THREAD

**Issue by Janebek** [VIS4ROB-lab/voxfield#8]
Hi! Thanks for your great work.

My question is that is voxfield capable of comibining with voxgraph?

**Comment by lucaBartolomei** [comment]
Hi! 

Sorry for the late reply. It think it should be possible. 

It should be sufficient to replace voxblox with voxfield in your catkin workspace, but I haven't tried myself. Maybe @YuePanEdward  can give more info about that.
